### PR TITLE
Update kue-ui dependency to upstream kue-ui-express

### PR DESCRIPTION
**Pull request by mdholloway**
Bug: https://phabricator.wikimedia.org/T177019

### CODE REVIEW

**Comment by mdholloway** [comment]
@nyurik Any objections?  I think this preserves the current functionality, but there might be nuance I'm missing as I'm relatively new to the project.

**Review by nyurik — COMMENTED** [review]
@mdholloway terribly sorry, i overlooked this PR. Unfortunately this specific functionality is mostly trial-and-error -- i had to poke it until it worked. I'm all for moving away from the custom builds, and it seems good for that :)

**Comment by thesocialdev** [comment]
Looks good to me. I will wait for @pnorman and @nyurik to merge this PR.

**Comment by nyurik** [comment]
@mdholloway feel free to merge :)  In Karotherian we usually use "owner merges after mandatory approval" model.

**Comment by mdholloway** [comment]
Sounds good, thanks @nyurik and @mateusbs17!

**Pull request merged**
